# HANDLING DATE AND TIME

In [39]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

In [40]:
# import both dataset
df1 = pd.read_csv('date.csv')
df2 = pd.read_csv('time.csv')

In [41]:
df1.head()

   ID        Date
0   1  2025-01-15
1   2  2025-02-20
2   3  2025-03-05
3   4  2025-04-12
4   5  2025-05-25

In [42]:
# convert date colum into date_time
df1['Date'] = pd.to_datetime(df1['Date'])

In [43]:
df1['date_year'] = df1['Date'].dt.year
# now for month
df1['date_month_no'] = df1['Date'].dt.month
# now for day
df1['date_day_no'] = df1['Date'].dt.day

In [44]:
df1.head()

   ID       Date  date_year  date_month_no  date_day_no
0   1 2025-01-15       2025              1           15
1   2 2025-02-20       2025              2           20
2   3 2025-03-05       2025              3            5
3   4 2025-04-12       2025              4           12
4   5 2025-05-25       2025              5           25

In [49]:
# now day of week 
df1['date_day_name'] = df1['Date'].dt.day_name()

# now for week day no
df1['date_week_day_no'] = df1['Date'].dt.weekday
df1['date_week_no'] = df1['Date'].dt.isocalendar().week

In [47]:
df1.head()

,ID,Date,date_year,date_month_no,date_day_no,date_day_name,date_week_day_no
0,1,2025-01-15,2025,1,15,Wednesday,2
1,2,2025-02-20,2025,2,20,Thursday,3
2,3,2025-03-05,2025,3,5,Wednesday,2
3,4,2025-04-12,2025,4,12,Saturday,5
4,5,2025-05-25,2025,5,25,Sunday,6

In [ ]:
df1['date_is_weekand'] = np.where(df1['date_day_name'].isin(['Saturday', 'Sunday']), 1, 0)

In [53]:
df1.head()

,ID,Date,date_year,date_month_no,date_day_no,date_day_name,date_week_day_no,date_week_no,is_weekand,date_is_weekand
0,1,2025-01-15,2025,1,15,Wednesday,2,3,2,0
1,2,2025-02-20,2025,2,20,Thursday,3,8,3,0
2,3,2025-03-05,2025,3,5,Wednesday,2,10,2,0
3,4,2025-04-12,2025,4,12,Saturday,5,15,5,1
4,5,2025-05-25,2025,5,25,Sunday,6,21,6,1